# Array

In [6]:
#Creating arrays
import numpy as np
a=np.array([1,2,3,4])
print(a)
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
#User input for array
l=[]
for i in range(1,6):
    x=int(input("Enter the element:"))
    l.append(x)
print(np.array(l))
print((np.array(l)).ndim)

Enter the element:1
Enter the element:2
Enter the element:3
Enter the element:4
Enter the element:5
[1 2 3 4 5]
1


In [12]:
#Creating 2-D array
ar2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
2


In [13]:
#Creating 3-D array
ar3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [15]:
#Creating n-D arrays
arn=np.array([1,2,3],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


# Creating numpy array using the numpy function

In [14]:
#Array filled with 0
import numpy as np
ar_zero=np.zeros((4,2))
print(ar_zero)
print(ar_zero.ndim)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
2


In [16]:
#Array filled with 1
ar_on=np.ones((4,3))
print(ar_on)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#Create an empty array
ar_em=np.empty((4,2))
print(ar_em)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
#Array with a range of element
ar_rn=np.arange(10)
print(ar_rn)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#Array diagonal element as 1
ar_d=np.eye(5)
print(ar_d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
#Array with specified intervals
ar_s=np.linspace(1,20,num=5)
print(ar_s)

[ 1.    5.75 10.5  15.25 20.  ]


# Creating numpy arrays with random values


In [38]:
#rand() 
var=np.random.rand(4)
var1=np.random.rand(4,4)
print(var)
print()
print(var1)

[0.53962847 0.64836654 0.36590872 0.05181165]

[[0.46550568 0.42072389 0.0589695  0.34310405]
 [0.18797483 0.08489295 0.82039531 0.12155569]
 [0.99602904 0.23952691 0.76968023 0.09971293]
 [0.2109479  0.0711242  0.93229414 0.83080114]]


In [39]:
#randn()
var2=np.random.randn(4)
print(var2)

[ 0.59910916 -0.20390771  1.37538989  0.96940554]


In [42]:
#randf
var3=np.random.ranf(4)
print(var3)

[0.82557851 0.39940639 0.07152975 0.07164067]


In [44]:
#randint
var4=np.random.randint(4,20,(10,5))
print(var4)

[[15  5  5 17 13]
 [14  8 18 17 10]
 [12 12  7  4  7]
 [ 7  7 17 14  9]
 [ 9 19  7  7 17]
 [17 11 16 11  7]
 [14 18  9  6 10]
 [ 5  9  6  5 13]
 [ 9 17  5  9  8]
 [11 12 10 19  9]]


# Data types in Numpy array

In [46]:
var=np.array([1,2,3,4])
print("Data Type:",var.dtype) 

Data Type: int32


In [47]:
var=np.array([1.0,2.3,3.4,4.5])
print("Data Type:",var.dtype)

Data Type: float64


In [48]:
var=np.array(["A","D","C"])
print("Data Type:",var.dtype)

Data Type: <U1


In [49]:
var=np.array(["A","S","F",1,2,3])
print("Data Type:",var.dtype)

Data Type: <U11


In [50]:
x=np.array([1,2,3,4],dtype=np.int8)
print("Data Type:",x.dtype)
print(x)

Data Type: int8
[1 2 3 4]


In [51]:
x=np.array([1,2,3,4],dtype="f")
print("Data Type:",x.dtype)
print(x)

Data Type: float32
[1. 2. 3. 4.]


In [52]:
x=np.array([1,2,3,4])
new=np.float32(x)
print("Data Type:",x.dtype)
print("Data Type:",new.dtype)
print(x)
print(new)

Data Type: int32
Data Type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [54]:
x=np.array([1,2,3,4])
new=np.float32(x)
new1=np.int32(new)
print("Data Type:",x.dtype)
print("Data Type:",new.dtype)
print("Data Type:",new1.dtype)
print(x)
print(new)
print(new1)

Data Type: int32
Data Type: float32
Data Type: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [55]:
x=np.array([1,2,3,4])
new1=x.astype(float)
print(x)
print(new1)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic operation in numpy arrays

In [57]:
#Addition in arrays
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [60]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
v=np.add(var1,var2)
r=np.reciprocal(var1)
print(r)
print(v)
print(varadd)

[1 0 0 0]
[2 4 6 8]
[2 4 6 8]


# Likewise all the operations can be perforemd in the arrays whether it's addition, subtraction,multiplication etc..

# Operations on 2-d arrays

In [62]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
v=np.add(var1,var2)
print(v)
print()
varadd=var1+var2
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]

[[2 4 6 8]
 [2 4 6 8]]


# Arithmetic Function in Numpy Arrays

In [72]:
var= np.array([1,2,3,4,5,3,8,9,2,3,4])
print("Min:",np.min(var))
print("Position of min:",np.argmin(var))
print("Max:",np.max(var))
print("Position of max:",np.argmax(var))
print("Squareroot:",np.sqrt(var))
print("Cumsum:",np.cumsum(var))


Min: 1
Position of min: 0
Max: 9
Position of max: 7
Squareroot: [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 2.82842712 3.         1.41421356 1.73205081 2.        ]
Cumsum: [ 1  3  6 10 15 18 26 35 37 40 44]


In [74]:
#2-D arrays
var1=np.array([[3,4,7,9],[1,0,7,9]])
print("Along axis-0:",np.min(var1,axis=0))
print("Along axis-1:",np.min(var1,axis=1))
print("Sqare root:",np.sqrt(var1))
print("Cumsum:",np.cumsum(var1,axis=0))
print("Cumsum:",np.cumsum(var1,axis=1))

Along axis-0: [1 0 7 9]
Along axis-1: [3 0]
Sqare root: [[1.73205081 2.         2.64575131 3.        ]
 [1.         0.         2.64575131 3.        ]]
Cumsum: [[ 3  4  7  9]
 [ 4  4 14 18]]
Cumsum: [[ 3  7 14 23]
 [ 1  1  8 17]]


# Shaping and Reshaping in Numpy Arrays

# shape

In [77]:
var=np.array([2,5,4,6,5],ndmin=4)
print(var)
print()
print(var.shape)

[[[[2 5 4 6 5]]]]

(1, 1, 1, 5)


In [80]:
#Dimension of the matrix generated
var=np.array([[2,3,4],[5,6,7]])
print(var)
print()
print(var.ndim)
print()
print(var.shape)

[[2 3 4]
 [5 6 7]]

2

(2, 3)


# Reshape

In [85]:
#1-D to 2-D
var=np.array([1,2,3,4,5,6])
print(var)
print()
x=var.reshape(2,3)
print(x)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [86]:
#2-D to 3-D
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print()
x=var.reshape(2,3,2)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [87]:
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print()
x=var.reshape(2,3,2)
print(x)
y=x.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# x.reshape(-1) converts the reshaped array into the 1-D array

In [93]:
var=np.array([[1,2,4,4]])
print(var.shape)
x=var.reshape(2,2)
print()
print(x)
print((x.reshape(-1).ndim))



(1, 4)

[[1 2]
 [4 4]]
1


# Broadcasting in numpy arrays

In [94]:
x=np.array([1,2,3,4])
y=np.array([1,2,3])
print(x,"\n")
print(y,"\n")
print(x+y)

[1 2 3 4] 

[1 2 3] 



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# operands could not be broadcast together with shapes (4,) (3,)

In [95]:
x=np.array([1,2,3,])
y=np.array([[1],[2],[3]])
print(x,"\n")
print(y,"\n")
print(x+y)

[1 2 3] 

[[1]
 [2]
 [3]] 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [102]:
x=np.array([1,2,3,1,2,3],ndmin=5)
y=np.array([[[1],[2],[3],[4],[5]]])
print(x,"\n")
print(x.shape)
print(y,"\n")
print(y.shape)
print(x+y)

[[[[[1 2 3 1 2 3]]]]] 

(1, 1, 1, 1, 6)
[[[1]
  [2]
  [3]
  [4]
  [5]]] 

(1, 5, 1)
[[[[[2 3 4 2 3 4]
    [3 4 5 3 4 5]
    [4 5 6 4 5 6]
    [5 6 7 5 6 7]
    [6 7 8 6 7 8]]]]]


# Indexing and slicing in numpy arrays

# INDEXING

In [3]:
#1-D array
import numpy as np
var=np.array([1,2,3,4])
#             0,1,2,3
#             -4,-3,-2,-1
print(var[0])
print(var[-1])

1
4


In [5]:
#2-D array
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print()
print(var1.ndim)
print()
print(var1[0,2])
#       (no. of row,no. of element)


[[9 8 7]
 [4 5 6]]

2

7


In [14]:
#3-D array
var2=np.array([[[9,8,7],[4,5,6],[1,2,3]],[[1,1,1],[1,2,3],[4,9,0]]])
print(var2)
print()
print(var2.ndim)
print()
print(var2[1,0,2])

[[[9 8 7]
  [4 5 6]
  [1 2 3]]

 [[1 1 1]
  [1 2 3]
  [4 9 0]]]

3

1


# SLICING

In [21]:
  #Slicing in 1-D array
x=np.array([2,4,6,8,10,12,14,16,18,20])
#           0,1,2,3, 4, 5, 6, 7, 8, 9
print(x)
print()
print("Elements from 2 to 12:",x[:6])
print()
print("Elements from 6 to end:",x[2:])
print()
print("Start to 14:",x[:7])
print()
print("using stop and step parameter:",x[1:7:2])
                                 #      [start,stop,step]
print(x[::2])

[ 2  4  6  8 10 12 14 16 18 20]

Elements from 2 to 12: [ 2  4  6  8 10 12]

Elements from 6 to end: [ 6  8 10 12 14 16 18 20]

Start to 14: [ 2  4  6  8 10 12 14]

using stop and step parameter: [ 4  8 12]
[ 2  6 10 14 18]


In [23]:
#Slicing in 2-D array
y=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(y)
print()
print("Element form 7 to 10:",y[1,1:])
             #                [row number,element index]
print()
print("Element from 6 to 10 with gap of 2:",y[1,0::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Element form 7 to 10: [ 7  8  9 10]

Element from 6 to 10 with gap of 2: [ 6  8 10]


In [28]:
#Slicing in 3-D array
z=np.array([[[1,2,3,5],[2,1,2,1]],[[3,4,7,8],[4,3,9,0]],[[6,7,4,5],[8,7,6,7]]])
print(z)
print()
print("Elements from 3 to 8: ",z[1,0,0:4])

[[[1 2 3 5]
  [2 1 2 1]]

 [[3 4 7 8]
  [4 3 9 0]]

 [[6 7 4 5]
  [8 7 6 7]]]

Elements from 3 to 8:  [3 4 7 8]


# ITERATING NUMPY ARRAY

In [31]:
#iterating 1-D array
p=np.array([4,5,6,7,8,9])
for i in p:
    print(i)

4
5
6
7
8
9


In [33]:
#iterating 2-d array
q=np.array([[1,2,3],[3,4,5],[6,7,8],[9,0,3]])
print(q)
print()
for i in q:
    print(i)
print()
for j in q:
    for k in j:
        print(k)


[[1 2 3]
 [3 4 5]
 [6 7 8]
 [9 0 3]]

[1 2 3]
[3 4 5]
[6 7 8]
[9 0 3]

1
2
3
3
4
5
6
7
8
9
0
3


In [37]:
#iterating 3-D array
r=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(r)
print()
for i in r:
    print("Row in r:",i)
print()
for j in r:
    for k in j:
        for l in k:
            print("Each element:",l)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]

Row in r: [[1 2 3]]
Row in r: [[4 5 6]]
Row in r: [[7 8 9]]

Each element: 1
Each element: 2
Each element: 3
Each element: 4
Each element: 5
Each element: 6
Each element: 7
Each element: 8
Each element: 9


# Using nditer()

In [38]:
r=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(r)
print()
for i in np.nditer(r):
    print(i)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]

1
2
3
4
5
6
7
8
9


# Using ndenumerate()

In [39]:
r=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(r)
print()
for i,d in np.ndenumerate(r):
    print(i,d)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 0, 2) 6
(2, 0, 0) 7
(2, 0, 1) 8
(2, 0, 2) 9


# Copy vs View in Numpy Arrays

In [41]:
#Copy
s=np.array([1,2,3,4])
c=s.copy()
s[1]=40                #changes amde in original array is not reflected 
print("Original:",s)   #in the copied array
print("Copied:",c)

Original: [ 1 40  3  4]
Copied: [1 2 3 4]


In [45]:
#View
t=np.array([1,2,3,4])
v=t.view()
t[3]=66               #changes made in any of the array will be reflected
v[0]=22               # in the both array.
print("Original:",t)
print("Copied:",v)

Original: [22  2  3 66]
Copied: [22  2  3 66]


# Join and Split function in Numpy Arrays

In [5]:
#concatnate two arrays 1-d array
import numpy as np
vr=np.array([1,2,3,4])
vr1=np.array([5,6,7,8])
new=np.concatenate((vr,vr1))
print(new)

[1 2 3 4 5 6 7 8]


In [11]:
#concatenate 2-D array
vr=np.array([[1,2],[3,4]])
vr1=np.array([[5,6],[7,8]])
new=np.concatenate((vr,vr1),axis=0)
new1=np.concatenate((vr,vr1),axis=1)
print(new)
print()
print(new1)
print(new.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]
2


In [87]:
# stack()
vr=np.array([1,2,3,4])
vr1=np.array([5,6,7,8])
new=np.stack((vr,vr1),axis=1) #axis can also be given
print(new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# Stack fun. is of three types:
    hstack(),vstack(),dstack().These eliminates the parameter axis to
    pass within the stack fun.

In [18]:
vr=np.array([1,2,3,4])
vr1=np.array([5,6,7,8])
new=np.hstack((vr,vr1))      #along row
new1=np.vstack((vr,vr1))      #along column
new2=np.dstack((vr,vr1))      #along height
print(vr)
print()
print(vr1)
print()
print("Merging along row:",new)
print()
print("Merging along column:",new1)
print()
print("Merging along height:",new2)

[1 2 3 4]

[5 6 7 8]

Merging along row: [1 2 3 4 5 6 7 8]

Merging along column: [[1 2 3 4]
 [5 6 7 8]]

Merging along height: [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# split array

In [89]:
var=np.array([1,2,3,4,5,6])
print(var)
print()
ar1=np.array_split(var,3)
                  #(variable name,no. of array user want)
print(ar1)
print()
print(type(ar1))
print(type(ar1[0]))

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
var=np.array([[1,2],[3,4],[5,6]])
print(var)
print()
ar1=np.array_split(var,3,axis=1)
                  #(variable name,no. of array user want,axis)
print(ar1)
print()
print(type(ar1))
print(type(ar1[0]))

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

<class 'list'>
<class 'numpy.ndarray'>


# NUMPY ARRAY FUNCTION

In [35]:
#Search array element
x=np.array([1,2,3,4,2,2,4,5,8,9,0,2])
        #   0,1,2,3,4,5,6,7,8,9,10,11
print(x)
print()
y=np.where((var%2)==0)
print(y)


[1 2 3 4 2 2 4 5 8 9 0 2]

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


In [34]:
var=np.array([4,2,3,4,2,5,2,5,6,7])
x=np.where( (var%2)==0)
print(x)

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


In [46]:
#Search sorted array
var=np.array([1,2,3,5,6,7,8,10,13,15])
print(var)
print()
v1=np.searchsorted(var,12)
print(v1)

[ 1  2  3  5  6  7  8 10 13 15]

8


# SORT

In [48]:
vp=np.array([59,67,3,5,6,71,0,8,10,13,15])
print(np.sort(vp))

[ 0  3  5  6  8 10 13 15 59 67 71]


In [49]:
vs=np.array(["Khushi","Kiran","Priy","Nutan"])
print(np.sort(vs))

['Khushi' 'Kiran' 'Nutan' 'Priy']


In [50]:
v=np.array([[5,2],[3,4],[1,7]])
print(np.sort(v))

[[2 5]
 [3 4]
 [1 7]]


In [51]:
#Filter Array
vs=np.array(["Khushi","Kiran","Priy","Nutan","jo","alu"])
f=[True,False,True,False,False,True]
print(vs[f])


['Khushi' 'Priy' 'alu']


In [53]:
#shuffling of data
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[4 5 1 2 3]


In [56]:
#removes the repition of the data using the unique()
v1=np.array([1,2,3,4,2,5,2,6,7])
x=np.unique(v1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


In [58]:
#change the size of the array using resize()
v2=np.array([1,2,3,4,5,6])
y=np.resize(v2,(3,2))                   
                #shape in which it is req. to be resized
print(y)

[[1 2 3]
 [4 5 6]]


In [65]:
#Flatten and ravel function are used to convert 2-D arrays into 1-D array
v2=np.array([1,2,3,4,5,6])
y=np.resize(v2,(3,2))
print(y)
print()
print("Flatten:",y.flatten(order="F")) #converted in 1-D array
#ravel()
print("Ravel:",np.ravel(y,order="F"))

[[1 2]
 [3 4]
 [5 6]]

Flatten: [1 3 5 2 4 6]
Ravel: [1 3 5 2 4 6]


# INSERT AND DELETE FUNCTIONS IN NUMPY ARRAYS

# INSERT

In [78]:
v=np.array([1,2,3,4])
print(v)
print()
vn=np.insert(v,3,40)
print(vn)
#if 40 is needed to be inserted in more than one index then,
print()
vnn=np.insert(v,(2,3),40)
print(vnn)
#Float value can't be inserted. it takes the integer part only
#inserting data using append function,
x=np.append(v,6.5)
print(x)

[1 2 3 4]

[ 1  2  3 40  4]

[ 1  2 40  3 40  4]
[1.  2.  3.  4.  6.5]


In [82]:
v2=np.array([[1,2,3],[4,5,6]])
v2n=np.insert(v2,2,40,axis=0)
v3n=np.insert(v2,2,40,axis=1)
         #   (array,posn,value,axis)
print(v2)
print()
print(v2n)
print()
print(v3n)
#if multiple value is required to be added in the array,
v4n=np.insert(v2,2,[20,23],axis=1)
print()
print(v4n)
print()
#inserting data into array using append function
v5n=np.append(v2,[[45,44,43]],axis=0)
print(v5n)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]]

[[ 1  2 40  3]
 [ 4  5 40  6]]

[[ 1  2 20  3]
 [ 4  5 23  6]]

[[ 1  2  3]
 [ 4  5  6]
 [45 44 43]]


# DELETE

In [83]:
var1=np.array([1,2,3,4])
print(var1)
print()
d=np.delete(var1,2)
print(d)

[1 2 3 4]

[1 2 4]


In [85]:
v2=np.array([[1,2,3],[4,5,6]])
print(v2)
print()
'''vn=np.delete(v2,[1,2])
print(vn)'''

[[1 2 3]
 [4 5 6]]

[1 4 5 6]


# MATRIX IN NUMPY ARRAY

In [3]:

# MATRIX IN NUMPY ARRAY
# Program to transpose a matrix

# FOCAL CELL
import numpy as np
v = np.array([[1, 2, 3], [4, 5, 6]])
transposed_v = np.transpose(v)
print(transposed_v)


[[1 4]
 [2 5]
 [3 6]]
